### ISSUE TITLE
[CLI] The CLI device built with default options goes to dead loop when thread is started

### ISSUE THREAD

**Issue by wgtdkp** [openthread/ot-nrf528xx#43]
The CLI device will be trapped in a dead loop when thread is started on the nrf52840 CLI device:
```txt
> ifconfig up
Done
> thread start
Done
> # hang
```

git commit: https://github.com/openthread/ot-nrf528xx/commit/993dc42f87cb905014593f417384eca33d2c6e6c
backtrace:
```txt
Program received signal SIGTRAP, Trace/breakpoint trap.
tx_terminate () at ../third_party/NordicSemiconductor/drivers/radio/nrf_802154_core.c:1181
1181	            while (!nrf_timer_event_check(NRF_802154_TIMER_INSTANCE, NRF_TIMER_EVENT_COMPARE0))
(gdb) bt
#0  tx_terminate () at ../third_party/NordicSemiconductor/drivers/radio/nrf_802154_core.c:1181
#1  0x00054b44 in current_operation_terminate (term_lvl=term_lvl@entry=1 '\001', 
    req_orig=req_orig@entry=REQ_ORIG_ACK_TIMEOUT, notify=notify@entry=false)
    at ../third_party/NordicSemiconductor/drivers/radio/nrf_802154_core.c:1400
#2  0x000558ee in nrf_802154_core_receive (term_lvl=<optimized out>, req_orig=<optimized out>, 
    notify_function=notify_function@entry=0x53911 <notify_tx_error>, notify_abort=<optimized out>)
    at ../third_party/NordicSemiconductor/drivers/radio/nrf_802154_core.c:2961
#3  0x00052a4e in nrf_802154_request_receive (term_lvl=term_lvl@entry=1 '\001', 
    req_orig=req_orig@entry=REQ_ORIG_ACK_TIMEOUT, notify_function=notify_function@entry=0x53911 <notify_tx_error>, 
    notify_abort=notify_abort@entry=false)
    at ../third_party/NordicSemiconductor/drivers/radio/nrf_802154_request_direct.c:67
#4  0x0005397a in timeout_timer_fired (p_context=<optimized out>)
    at ../third_party/NordicSemiconductor/drivers/radio/mac_features/nrf_802154_precise_ack_timeout.c:75
#5  0x00052968 in nrf_802154_lp_timer_fired ()
    at ../third_party/NordicSemiconductor/drivers/radio/timer_scheduler/nrf_802154_timer_sched.c:465
#6  0x0000822c in HandleCompareMatch (aIndex=aIndex@entry=k802154Timer, aSkipCheck=aSkipCheck@entry=false)
    at ../src/src/alarm.c:319
#7  0x00008856 in RTC2_IRQHandler () at ../src/src/alarm.c:686
#8  <signal handler called>
#9  nrf5RadioProcess (aInstance=aInstance@entry=0x20001388 <ot::gInstanceRaw>) at ../src/src/radio.c:831
#10 0x00007df8 in otSysProcessDrivers (aInstance=aInstance@entry=0x20001388 <ot::gInstanceRaw>)
    at ../src/src/system.c:141
#11 0x00000620 in main (argc=0, argv=0x0 <__isr_vector>) at ../openthread/examples/apps/cli/main.c:123
(gdb)
```

Steps to reproduce:
1. build and flash the nrf52840 CLI device by following https://github.com/openthread/ot-nrf528xx/blob/main/src/nrf52840/README.md
2. start GDB debugging by following https://devzone.nordicsemi.com/nordic/nrf-connect-sdk-guides/b/getting-started/posts/using-gdb-with-nordic-devices
3. start thread on the CLI device with `ifconfig up` and `thread start` commands.

**Comment by wgtdkp** [comment]
@LuDuda Could you help take a look?

**Comment by wgtdkp** [comment]
This issue disappears with another DK board.
